import MainLayout from "@/components/Layout";
import StyledComponentsRegistry from "@/lib/styledComponentRegistry";
import { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Next E-Commerce",
  description: "Generated by bulutme",
  keywords: "e-commerce, shopping, product",
  icons: {
    icon: "/next.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={poppins.className}>
        <Suspense fallback={<Loading />}>
          <StyledComponentsRegistry>
            <MainLayout>{children}</MainLayout>
          </StyledComponentsRegistry>
        </Suspense>
      </body>
    </html>
  );
}
